# Generated by Django 2.1 on 2018-09-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('subject', models.CharField(choices=[('A', 'Subject'), ('B', 'Feedback'), ('C', 'Order')], default='A', max_length=100)),
                ('message', models.CharField(max_length=800)),
            ],
        ),
    ]
